// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218212340_UpdateUsersTable")]
    partial class UpdateUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Shopify.ShopifyCustomer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Addresses")
                        .HasColumnType("text")
                        .HasColumnName("addresses");

                    b.Property<string>("AdminGraphqlApiId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_graphql_api_id");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("DefaultAddress")
                        .HasColumnType("text")
                        .HasColumnName("default_address");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailMarketingConsent")
                        .HasColumnType("text")
                        .HasColumnName("email_marketing_consent");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("InternalCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("InternalUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("InternalUpdatedAt"));

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<long?>("LastOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_order_id");

                    b.Property<string>("LastOrderName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_order_name");

                    b.Property<string>("MultipassIdentifier")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("multipass_identifier");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("int")
                        .HasColumnName("orders_count");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SmsMarketingConsent")
                        .HasColumnType("text")
                        .HasColumnName("sms_marketing_consent");

                    b.Property<string>("State")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tax_exempt");

                    b.Property<string>("TaxExemptions")
                        .HasColumnType("text")
                        .HasColumnName("tax_exemptions");

                    b.Property<string>("TotalSpent")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_spent");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VerifiedEmail")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("verified_email");

                    b.HasKey("Id")
                        .HasName("p_k_shopify_customers");

                    b.HasIndex("AdminGraphqlApiId")
                        .IsUnique()
                        .HasDatabaseName("i_x_shopify_customers_admin_graphql_api_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("i_x_shopify_customers_email");

                    b.ToTable("shopify_customers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Shopify.ShopifyOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AdminGraphqlApiId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_graphql_api_id");

                    b.Property<long?>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text")
                        .HasColumnName("billing_address");

                    b.Property<string>("BrowserIp")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("browser_ip");

                    b.Property<bool>("BuyerAcceptsMarketing")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("buyer_accepts_marketing");

                    b.Property<string>("CancelReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CartToken")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cart_token");

                    b.Property<long?>("CheckoutId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_id");

                    b.Property<string>("CheckoutToken")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("checkout_token");

                    b.Property<string>("ClientDetails")
                        .HasColumnType("text")
                        .HasColumnName("client_details");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("closed_at");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("confirmation_number");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("confirmed");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrentSubtotalPrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("current_subtotal_price");

                    b.Property<string>("CurrentSubtotalPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("current_subtotal_price_set");

                    b.Property<string>("CurrentTotalAdditionalFeesSet")
                        .HasColumnType("text")
                        .HasColumnName("current_total_additional_fees_set");

                    b.Property<string>("CurrentTotalDiscounts")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("current_total_discounts");

                    b.Property<string>("CurrentTotalDiscountsSet")
                        .HasColumnType("text")
                        .HasColumnName("current_total_discounts_set");

                    b.Property<string>("CurrentTotalDutiesSet")
                        .HasColumnType("text")
                        .HasColumnName("current_total_duties_set");

                    b.Property<string>("CurrentTotalPrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("current_total_price");

                    b.Property<string>("CurrentTotalPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("current_total_price_set");

                    b.Property<string>("CurrentTotalTax")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("current_total_tax");

                    b.Property<string>("CurrentTotalTaxSet")
                        .HasColumnType("text")
                        .HasColumnName("current_total_tax_set");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<string>("CustomerLocale")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("customer_locale");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("DiscountApplications")
                        .HasColumnType("text")
                        .HasColumnName("discount_applications");

                    b.Property<string>("DiscountCodes")
                        .HasColumnType("text")
                        .HasColumnName("discount_codes");

                    b.Property<bool?>("DutiesIncluded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("duties_included");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EstimatedTaxes")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estimated_taxes");

                    b.Property<string>("FinancialStatus")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("financial_status");

                    b.Property<string>("FulfillmentStatus")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fulfillment_status");

                    b.Property<string>("Fulfillments")
                        .HasColumnType("text")
                        .HasColumnName("fulfillments");

                    b.Property<DateTime>("InternalCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("InternalUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("InternalUpdatedAt"));

                    b.Property<string>("LandingSite")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("landing_site");

                    b.Property<string>("LandingSiteRef")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("landing_site_ref");

                    b.Property<string>("LineItems")
                        .HasColumnType("text")
                        .HasColumnName("line_items");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<string>("MerchantBusinessEntityId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("merchant_business_entity_id");

                    b.Property<long?>("MerchantOfRecordAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("merchant_of_record_app_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NoteAttributes")
                        .HasColumnType("text")
                        .HasColumnName("note_attributes");

                    b.Property<long?>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<long?>("OrderNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatusUrl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_status_url");

                    b.Property<string>("OriginalTotalAdditionalFeesSet")
                        .HasColumnType("text")
                        .HasColumnName("original_total_additional_fees_set");

                    b.Property<string>("OriginalTotalDutiesSet")
                        .HasColumnType("text")
                        .HasColumnName("original_total_duties_set");

                    b.Property<string>("PaymentGatewayNames")
                        .HasColumnType("text")
                        .HasColumnName("payment_gateway_names");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PresentmentCurrency")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("presentment_currency");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reference")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reference");

                    b.Property<string>("ReferringSite")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("referring_site");

                    b.Property<string>("Refunds")
                        .HasColumnType("text")
                        .HasColumnName("refunds");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address");

                    b.Property<string>("ShippingLines")
                        .HasColumnType("text")
                        .HasColumnName("shipping_lines");

                    b.Property<string>("SourceIdentifier")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_identifier");

                    b.Property<string>("SourceName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_url");

                    b.Property<string>("SubtotalPrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("subtotal_price");

                    b.Property<string>("SubtotalPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("subtotal_price_set");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<bool?>("TaxExempt")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tax_exempt");

                    b.Property<string>("TaxLines")
                        .HasColumnType("text")
                        .HasColumnName("tax_lines");

                    b.Property<bool?>("TaxesIncluded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("taxes_included");

                    b.Property<bool?>("Test")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("test");

                    b.Property<string>("Token")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("token");

                    b.Property<string>("TotalCashRoundingPaymentAdjustmentSet")
                        .HasColumnType("text")
                        .HasColumnName("total_cash_rounding_payment_adjustment_set");

                    b.Property<string>("TotalCashRoundingRefundAdjustmentSet")
                        .HasColumnType("text")
                        .HasColumnName("total_cash_rounding_refund_adjustment_set");

                    b.Property<string>("TotalDiscounts")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_discounts");

                    b.Property<string>("TotalDiscountsSet")
                        .HasColumnType("text")
                        .HasColumnName("total_discounts_set");

                    b.Property<string>("TotalLineItemsPrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_line_items_price");

                    b.Property<string>("TotalLineItemsPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("total_line_items_price_set");

                    b.Property<string>("TotalOutstanding")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_outstanding");

                    b.Property<string>("TotalPrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_price");

                    b.Property<string>("TotalPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("total_price_set");

                    b.Property<string>("TotalShippingPriceSet")
                        .HasColumnType("text")
                        .HasColumnName("total_shipping_price_set");

                    b.Property<string>("TotalTax")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_tax");

                    b.Property<string>("TotalTaxSet")
                        .HasColumnType("text")
                        .HasColumnName("total_tax_set");

                    b.Property<string>("TotalTipReceived")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total_tip_received");

                    b.Property<int?>("TotalWeight")
                        .HasColumnType("int")
                        .HasColumnName("total_weight");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_shopify_orders");

                    b.HasIndex("Cpf")
                        .HasDatabaseName("i_x_shopify_orders_cpf");

                    b.ToTable("shopify_orders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Shopify.ShopifyProducts", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AdminGraphqlApiId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_graphql_api_id");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Handle")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("handle");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Images")
                        .HasColumnType("text")
                        .HasColumnName("images");

                    b.Property<DateTime>("InternalCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("InternalUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("internal_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("InternalUpdatedAt"));

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<string>("ProductType")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("product_type");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at");

                    b.Property<string>("PublishedScope")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("published_scope");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateSuffix")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("template_suffix");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variants")
                        .HasColumnType("text")
                        .HasColumnName("variants");

                    b.Property<string>("Vendor")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("p_k_shopify_products");

                    b.HasIndex("AdminGraphqlApiId")
                        .IsUnique()
                        .HasDatabaseName("i_x_shopify_products_admin_graphql_api_id");

                    b.HasIndex("Handle")
                        .HasDatabaseName("i_x_shopify_products_handle");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_shopify_products_status");

                    b.ToTable("shopify_products", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
