namespace Domain.Entities.Shopify;

public class ShopifyOrder
{
    public long Id { get; set; }
    public string? Cpf { get; set; }
    public string? AdminGraphqlApiId { get; set; }
    public long? AppId { get; set; }
    public string? BrowserIp { get; set; }
    public bool BuyerAcceptsMarketing { get; set; }
    public string? CancelReason { get; set; }
    public DateTime? CancelledAt { get; set; }
    public string? CartToken { get; set; }
    public long? CheckoutId { get; set; }
    public string? CheckoutToken { get; set; }
    public string? ClientDetails { get; set; }
    public DateTime? ClosedAt { get; set; }
    public string? ConfirmationNumber { get; set; }
    public bool Confirmed { get; set; }
    public string? ContactEmail { get; set; }
    public DateTime CreatedAt { get; set; }
    public string? Currency { get; set; }
    public string? CurrentSubtotalPrice { get; set; }
    public string? CurrentSubtotalPriceSet { get; set; }
    public string? CurrentTotalAdditionalFeesSet { get; set; }
    public string? CurrentTotalDiscounts { get; set; }
    public string? CurrentTotalDiscountsSet { get; set; }
    public string? CurrentTotalDutiesSet { get; set; }
    public string? CurrentTotalPrice { get; set; }
    public string? CurrentTotalPriceSet { get; set; }
    public string? CurrentTotalTax { get; set; }
    public string? CurrentTotalTaxSet { get; set; }
    public string? CustomerLocale { get; set; }
    public long? DeviceId { get; set; }
    public string? DiscountCodes { get; set; }
    public bool? DutiesIncluded { get; set; }
    public string? Email { get; set; }
    public bool? EstimatedTaxes { get; set; }
    public string? FinancialStatus { get; set; }
    public string? FulfillmentStatus { get; set; }
    public string? LandingSite { get; set; }
    public string? LandingSiteRef { get; set; }
    public long? LocationId { get; set; }
    public string? MerchantBusinessEntityId { get; set; }
    public long? MerchantOfRecordAppId { get; set; }
    public string? Name { get; set; }
    public string? Note { get; set; }
    public string? NoteAttributes { get; set; }
    public long? Number { get; set; }
    public long? OrderNumber { get; set; }
    public string? OrderStatusUrl { get; set; }
    public string? OriginalTotalAdditionalFeesSet { get; set; }
    public string? OriginalTotalDutiesSet { get; set; }
    public string? PaymentGatewayNames { get; set; }
    public string? Phone { get; set; }
    public string? PresentmentCurrency { get; set; }
    public DateTime ProcessedAt { get; set; }
    public string? Reference { get; set; }
    public string? ReferringSite { get; set; }
    public string? SourceIdentifier { get; set; }
    public string? SourceName { get; set; }
    public string? SourceUrl { get; set; }
    public string? SubtotalPrice { get; set; }
    public string? SubtotalPriceSet { get; set; }
    public string? Tags { get; set; }
    public bool? TaxExempt { get; set; }
    public string? TaxLines { get; set; }
    public bool? TaxesIncluded { get; set; }
    public bool? Test { get; set; }
    public string? Token { get; set; }
    public string? TotalCashRoundingPaymentAdjustmentSet { get; set; }
    public string? TotalCashRoundingRefundAdjustmentSet { get; set; }
    public string? TotalDiscounts { get; set; }
    public string? TotalDiscountsSet { get; set; }
    public string? TotalLineItemsPrice { get; set; }
    public string? TotalLineItemsPriceSet { get; set; }
    public string? TotalOutstanding { get; set; }
    public string? TotalPrice { get; set; }
    public string? TotalPriceSet { get; set; }
    public string? TotalShippingPriceSet { get; set; }
    public string? TotalTax { get; set; }
    public string? TotalTaxSet { get; set; }
    public string? TotalTipReceived { get; set; }
    public long? TotalWeight { get; set; }
    public DateTime UpdatedAt { get; set; }
    public long? UserId { get; set; }
    public string? BillingAddress { get; set; }
    public string? Customer { get; set; }
    public string? DiscountApplications { get; set; }
    public string? Fulfillments { get; set; }
    public string? LineItems { get; set; }
    public string? PaymentTerms { get; set; }
    public string? Refunds { get; set; }
    public string? ShippingAddress { get; set; }
    public string? ShippingLines { get; set; }
    public DateTime? InternalCreatedAt { get; set; }
    public DateTime? InternalUpdatedAt { get; set; }
}
